[project]
name = "iqm"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">= 3.11, < 3.13"
dependencies = [
    "iqm-client[qiskit]>=33.0.3",
    "matplotlib>=3.10.8",
    "ortools>=9.9.3963",
    "qrisp[iqm]>=0.7.19",
]
